name: Update Image List
on:
  push:
    paths:
      - 'images/**'  # Watch all subdirectories under /images

jobs:
  generate-image-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate structured image list
        id: generate-list
        run: |
          # Create nested JSON structure
          find images -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" \) | \
            jq -R -n '
              [inputs | sub("^images/"; "") | split("/")] |
              reduce .[] as $img (
                {};
                .[$img[0]] += [$img[1]]
              )
            ' > images.json

          # Check for changes
          git diff --exit-code images.json || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.generate-list.outputs.changed == 'true'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add images.json
          git commit -m "Auto-update structured image list"
          git push
